# Generated by Django 2.2.7 on 2019-11-10 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CS361', max_length=20)),
                ('isCourseFull', models.BooleanField(default=False)),
                ('startTime', models.TimeField(default=datetime.datetime.now, verbose_name='Start Time:')),
                ('endTime', models.TimeField(default=datetime.datetime.now, verbose_name='Start Time:')),
                ('dates', models.CharField(default='MTWRFS', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('PROF', 'Professor'), ('TA', 'TA / Grader')], default='TA', max_length=5)),
            ],
        ),
    ]
