# Generated by Django 2.2.6 on 2019-12-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAmanage', '0003_auto_20191110_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
