# Generated by Django 2.2.6 on 2019-12-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAmanage', '0004_auto_20191204_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='section',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, default='Online', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='CS000', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='officeHours',
            field=models.CharField(blank=True, default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='officeHoursDates',
            field=models.CharField(blank=True, default='None', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='officeLocation',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='None', max_length=15, null=True),
        ),
    ]
