# Generated by Django 2.2.6 on 2019-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAmanage', '0005_auto_20191204_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isCourseFull',
            field=models.BooleanField(default=False),
        ),
    ]
