# Generated by Django 3.0 on 2019-12-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAmanage', '0006_course_iscoursefull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='isCourseFull',
        ),
    ]
